# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  githubID: yiliyil
  repository: demo-java-app
  tag: V1.0-amd64
  pullPolicy: IfNotPresent

appName: demo-java-app

namespace: app

kibanaService: "kibana-service:5601"
esService: "es-master-service:9200"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  name: ""

service:
  type: ClusterIP

ingress:
  enabled: false
